global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nezam.identity'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'identity-api:8080' ]  # Use the Docker service name and container port
